// Generated by scripts/brand/extract-logo-layers.py. Do not edit by hand.
// Layer rectangles are [x, y, width, height] on each logo canvas; the files
// live in public/brand/logo.

export const BRAND_LOGOS = {
  'emblem': {
    width: 1188,
    height: 1100,
    layers: {
      'n1': [4, 234, 501, 780],
      'i1': [358, 316, 154, 292],
      'g1': [454, 276, 246, 288],
      'h1': [617, 248, 281, 290],
      't1': [860, 196, 280, 288],
      'l2': [138, 554, 214, 321],
      'i2': [330, 574, 152, 259],
      'g2': [425, 526, 259, 280],
      'h2': [594, 483, 291, 305],
      't2': [848, 444, 292, 332],
      'bolt': [949, 239, 239, 237],
      'frame': [68, 44, 1120, 1032],
      'arcs': [0, 0, 1132, 1100],
    },
  },
  'wordmark': {
    width: 1766,
    height: 688,
    layers: {
      'n': [34, 158, 421, 500],
      'i': [305, 300, 145, 216],
      'g': [393, 281, 232, 206],
      'h': [552, 264, 255, 223],
      't': [787, 241, 201, 219],
      'l': [921, 236, 150, 195],
      'i2': [1052, 221, 136, 194],
      'g2': [1132, 203, 211, 197],
      'h2': [1274, 185, 229, 214],
      't2': [1486, 165, 207, 224],
      'bolt': [1488, 175, 242, 342],
      'rule-top': [391, 103, 1353, 201],
      'rule-bottom': [196, 388, 1302, 211],
      'arcs': [0, 0, 1766, 688],
    },
  },
} as const

export type BrandLogo = keyof typeof BRAND_LOGOS
