<script setup lang="ts">
import { apiErrorMessage } from '~/utils/api-error'
definePageMeta({ layout: 'admin' })
type Settings = { companyName:string;address:string;postalCode:string;city:string;country:string;email:string;phone:string;registrationNumber:string;vatNumber:string;iban:string;invoicePrefix:string;nextInvoiceNumber:number;defaultVatMode:'exclusive'|'inclusive'|'exempt';defaultVatRateBasisPoints:number;defaultPaymentTermDays:number;paymentTerms:string;legalText:string }
const {data,refresh}=await useFetch<{settings:Settings}>('/api/admin/business-settings')
if(!data.value)throw createError({statusCode:500,statusMessage:'Business settings unavailable'})
const form=reactive({...data.value.settings});const saving=ref(false);const message=ref('')
function setVatRate(event:Event){form.defaultVatRateBasisPoints=Math.round(Number((event.target as HTMLInputElement).value)*100)}
async function save(){saving.value=true;message.value='';try{await $fetch('/api/admin/business-settings',{method:'PUT',body:form});await refresh();message.value='Business and invoice defaults saved.'}catch(error:unknown){message.value=apiErrorMessage(error,'Could not save settings.')}finally{saving.value=false}}
useSeoMeta({title:'Settings — DJ NightLight',robots:'noindex, nofollow'})
</script>
<template><div class="settings"><header><p class="eyebrow">System</p><h1>Business settings</h1><p>These defaults are copied into each finalized invoice so later changes never rewrite invoice history.</p></header><form @submit.prevent="save"><section class="card"><h2>Company</h2><div class="grid"><label class="wide">Company name<input v-model="form.companyName" required></label><label class="wide">Address<input v-model="form.address"></label><label>Postal code<input v-model="form.postalCode"></label><label>City<input v-model="form.city"></label><label>Country<input v-model="form.country"></label><label>Email<input v-model="form.email" type="email"></label><label>Phone<input v-model="form.phone"></label><label>Registration / KVK<input v-model="form.registrationNumber"></label><label>VAT number<input v-model="form.vatNumber"></label><label>IBAN<input v-model="form.iban"></label></div></section><section class="card"><h2>Invoice defaults</h2><div class="grid"><label>Number prefix<input v-model="form.invoicePrefix" required></label><label>Next sequence<input :value="form.nextInvoiceNumber" disabled><small>Advanced automatically on finalization.</small></label><label>VAT behavior<select v-model="form.defaultVatMode"><option value="exclusive">Prices excluding VAT</option><option value="inclusive">Prices including VAT</option><option value="exempt">No VAT / exempt</option></select></label><label>VAT rate (%)<input :value="form.defaultVatRateBasisPoints/100" type="number" min="0" max="100" step="0.01" @input="setVatRate"></label><label>Payment term (days)<input v-model.number="form.defaultPaymentTermDays" type="number" min="0" max="365"></label><label class="wide">Payment terms<textarea v-model="form.paymentTerms" rows="3"/></label><label class="wide">Legal text<textarea v-model="form.legalText" rows="3"/></label></div></section><div class="save"><span>{{message}}</span><button :disabled="saving">{{saving?'Saving…':'Save settings'}}</button></div></form></div></template>
<style scoped>.settings{max-width:900px;margin-inline:auto}header{margin-bottom:1.5rem}h1{margin:.2rem 0;font-size:clamp(2.5rem,6vw,4.5rem);letter-spacing:-.05em}header>p:last-child{max-width:680px;color:#8c8594}.card{margin-bottom:1rem;padding:1.2rem;border:1px solid #2b2631;border-radius:1rem;background:#100e14}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.wide{grid-column:1/-1}label{display:grid;gap:.35rem;color:#aaa4b1;font-size:.8rem}label small{color:#716a78}input,select,textarea{width:100%;border:1px solid #332e39;border-radius:.65rem;padding:.7rem;background:#0b0a0d;color:#f6f3fa}.save{display:flex;align-items:center;justify-content:space-between;gap:1rem}.save span{color:#aaa4b1}.save button{border:0;border-radius:.7rem;padding:.75rem 1rem;background:#fff;color:#09080b;font-weight:800}@media(max-width:650px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.save{align-items:stretch;flex-direction:column}.save button{width:100%}}</style>
