CREATE TABLE IF NOT EXISTS "site_content" (
  "key" varchar(40) PRIMARY KEY NOT NULL,
  "brand_name" varchar(120) NOT NULL,
  "hero_eyebrow" varchar(160) NOT NULL,
  "hero_title" varchar(300) NOT NULL,
  "hero_body" text NOT NULL,
  "hero_image_url" text,
  "hero_cta_label" varchar(120) NOT NULL,
  "about_eyebrow" varchar(160) NOT NULL,
  "about_title" varchar(300) NOT NULL,
  "about_body" text NOT NULL,
  "media_eyebrow" varchar(160) NOT NULL,
  "media_title" varchar(300) NOT NULL,
  "media_body" text NOT NULL,
  "showreel_url" text,
  "agenda_eyebrow" varchar(160) NOT NULL,
  "agenda_title" varchar(300) NOT NULL,
  "agenda_body" text NOT NULL,
  "booking_eyebrow" varchar(160) NOT NULL,
  "booking_title" varchar(300) NOT NULL,
  "booking_body" text NOT NULL,
  "contact_email" varchar(320),
  "contact_phone" varchar(64),
  "instagram_url" text,
  "spotify_url" text,
  "seo_title" varchar(180) NOT NULL,
  "seo_description" varchar(320) NOT NULL,
  "seo_image_url" text,
  "services" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "gallery" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);

INSERT INTO "site_content" (
  "key", "brand_name", "hero_eyebrow", "hero_title", "hero_body", "hero_cta_label",
  "about_eyebrow", "about_title", "about_body",
  "media_eyebrow", "media_title", "media_body",
  "agenda_eyebrow", "agenda_title", "agenda_body",
  "booking_eyebrow", "booking_title", "booking_body",
  "seo_title", "seo_description", "services", "gallery"
) VALUES (
  'default',
  'DJ NightLight',
  'Allround DJ · Groningen',
  'Van eerste plaat tot laatste dans.',
  'Een avond die rustig kan beginnen en precies op het juiste moment losgaat. DJ NightLight draait breed, leest de zaal en bouwt de energie op rond jouw publiek.',
  'Boek NightLight',
  'Over NightLight',
  'Niet één vaste set. Wel de juiste muziek voor de zaal.',
  'DJ NightLight draait op bruiloften, clubavonden, studentenfeesten, bedrijfsfeesten en privé-events. De muziek beweegt mee met het publiek: herkenbaar waar het moet, verrassend waar het kan.',
  'Media',
  'Zie en hoor de sfeer.',
  'Foto''s, sets en showreels komen hier samen. Nieuwe media kun je vanuit het NightLight-beheer publiceren zonder de websitecode aan te passen.',
  'Agenda',
  'Waar draait NightLight?',
  'Openbare shows verschijnen hier. Besloten boekingen blijven vanzelfsprekend privé.',
  'Boeken',
  'Vertel wat je aan het plannen bent.',
  'Stuur de datum, locatie en het soort feest. Je aanvraag komt direct als lead in het NightLight-systeem terecht.',
  'DJ NightLight · DJ voor feesten, clubs en bruiloften',
  'DJ NightLight uit Groningen voor bruiloften, clubs, studentenfeesten, bedrijfsfeesten en privé-events.',
  '[{"title":"Bruiloften","body":"Van ontvangst en diner tot openingsdans en volle dansvloer, met ruimte voor jullie eigen muziek."},{"title":"Clubs & studentenfeesten","body":"Tempo, herkenning en energie. Flexibel tussen house, pop, guilty pleasures en alles wat de zaal nodig heeft."},{"title":"Bedrijfs- & privéfeesten","body":"Een muzikale opbouw die past bij de groep, de locatie en het moment."}]'::jsonb,
  '[]'::jsonb
)
ON CONFLICT ("key") DO NOTHING;
