<script setup lang="ts">
definePageMeta({layout:'public'})
const {data}=await useSiteContent();const content=computed(()=>data.value?.content)
useSeoMeta({title:()=>`Over — ${content.value?.brandName||'DJ NightLight'}`,description:()=>content.value?.aboutBody})
</script>
<template><main v-if="content" class="public-page"><div class="public-container"><p class="eyebrow">{{content.aboutEyebrow}}</p><h1 class="display-title">{{content.aboutTitle}}</h1><div class="story"><p>{{content.aboutBody}}</p><aside><span>NightLight</span><strong>Allround, maar nooit willekeurig.</strong><p>De set volgt de avond: achtergrond waar het moet, herkenning wanneer de groep samenkomt en energie zodra de dansvloer er klaar voor is.</p></aside></div><section class="principles"><article><span>01</span><h2>Lezen</h2><p>Geen vooraf dichtgetimmerde playlist. Eerst kijken wat de zaal nodig heeft.</p></article><article><span>02</span><h2>Opbouwen</h2><p>Een feest hoeft niet om 20:00 al op 100%. De energie mag groeien.</p></article><article><span>03</span><h2>Schakelen</h2><p>Van klassieker naar house, van pop naar guilty pleasure — zolang de overgang klopt.</p></article></section></div></main></template>
<style scoped>
.story{display:grid;grid-template-columns:1.25fr .75fr;gap:clamp(2rem,7vw,7rem);align-items:start}.story>p{margin:0;color:#aaa4af;font-size:clamp(1.15rem,2.4vw,1.6rem);line-height:1.7}.story aside{padding:1.5rem;border-left:1px solid #322d37}.story aside span,.principles span{color:#68616e;font-size:.7rem;letter-spacing:.1em;text-transform:uppercase}.story aside strong{display:block;margin:.7rem 0;font-size:1.35rem}.story aside p{color:#88828e;line-height:1.6}.principles{display:grid;grid-template-columns:repeat(3,1fr);margin-top:8rem;border-top:1px solid #28242d}.principles article{padding:1.5rem 1.2rem;border-right:1px solid #28242d}.principles article:last-child{border:0}.principles h2{margin:4rem 0 .5rem}.principles p{color:#89838f;line-height:1.6}@media(max-width:760px){.story,.principles{grid-template-columns:1fr}.story aside{border-left:0;border-top:1px solid #322d37}.principles{margin-top:4rem}.principles article{border-right:0;border-bottom:1px solid #28242d}.principles h2{margin:2rem 0 .5rem}}
</style>
