<script setup lang="ts">
definePageMeta({layout:'public'})
const {data}=await useSiteContent();const content=computed(()=>data.value?.content)
useSeoMeta({title:()=>`Media — ${content.value?.brandName||'DJ NightLight'}`,description:()=>content.value?.mediaBody})
</script>
<template><main v-if="content" class="public-page"><div class="public-container"><p class="eyebrow">{{content.mediaEyebrow}}</p><h1 class="display-title">{{content.mediaTitle}}</h1><p class="lead-copy">{{content.mediaBody}}</p><div v-if="content.showreelUrl" class="showreel"><a class="public-button secondary" :href="content.showreelUrl" target="_blank" rel="noreferrer">Bekijk showreel ↗</a></div><section v-if="content.gallery.length" class="gallery"><figure v-for="(image,index) in content.gallery" :key="`${image.url}-${index}`"><img :src="image.url" :alt="image.alt" loading="lazy"><figcaption v-if="image.alt">{{image.alt}}</figcaption></figure></section><section v-else class="empty-media"><span>Media library</span><strong>Nog geen beelden gepubliceerd.</strong><p>Voeg vanuit de back office foto's toe zodra je de eerste selectie klaar hebt.</p></section></div></main></template>
<style scoped>
.showreel{margin-top:1.5rem}.gallery{display:grid;grid-template-columns:repeat(12,1fr);gap:.8rem;margin-top:4rem}.gallery figure{grid-column:span 6;margin:0;overflow:hidden;border-radius:.8rem;background:#121015}.gallery figure:nth-child(3n){grid-column:span 12}.gallery img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.gallery figure:nth-child(3n) img{aspect-ratio:16/7}.gallery figcaption{padding:.7rem;color:#7c7682;font-size:.75rem}.empty-media{display:grid;min-height:20rem;align-content:end;gap:.5rem;margin-top:4rem;padding:1.5rem;border:1px solid #27232b;border-radius:1rem;background:radial-gradient(circle at 70% 20%,rgba(93,56,176,.2),transparent 30%),#0e0c11}.empty-media span{color:#68616e;font-size:.7rem;text-transform:uppercase;letter-spacing:.1em}.empty-media strong{font-size:1.5rem}.empty-media p{max-width:30rem;margin:0;color:#817b86}@media(max-width:700px){.gallery figure,.gallery figure:nth-child(3n){grid-column:span 12}.gallery figure:nth-child(3n) img{aspect-ratio:4/3}}
</style>
