<script setup lang="ts">
import { calculateInvoiceTotals } from '~~/shared/invoice'
import { apiErrorMessage } from '~/utils/api-error'
definePageMeta({layout:'admin'})
const route=useRoute();const id=String(route.params.id)
type Line={id:string;description:string;quantity:string;unitPriceCents:number;ordering:number}
type Invoice={id:string;invoiceNumber:string|null;status:'draft'|'finalized'|'void';paymentStatus:string;issueDate:string;dueDate:string;currency:string;vatMode:'exclusive'|'inclusive'|'exempt';vatRateBasisPoints:number;subtotalCents:number;vatAmountCents:number;totalCents:number;paymentTerms:string;legalText:string;notes:string;documentHash:string|null;gigId:string;gigTitle:string;clientFirstName:string|null;clientLastName:string|null;clientCompanyName:string|null}
type Detail={invoice:Invoice;lines:Line[];payment:{providerSessionId:string|null;providerPaymentIntentId:string|null;status:string;attemptCount:number;paidAt:string|null;failureCode:string|null}|null}
type EditableLine={description:string;quantity:string;unitPrice:string}
const {data,refresh}=await useFetch<Detail>(`/api/admin/invoices/${id}`)
if(!data.value)throw createError({statusCode:404,statusMessage:'Invoice not found'})
const invoice=data.value.invoice
const form=reactive({issueDate:invoice.issueDate,dueDate:invoice.dueDate,currency:invoice.currency,vatMode:invoice.vatMode,vatRateBasisPoints:invoice.vatRateBasisPoints,paymentTerms:invoice.paymentTerms,legalText:invoice.legalText,notes:invoice.notes})
const lines=ref<EditableLine[]>(data.value.lines.map(line=>({description:line.description,quantity:String(line.quantity),unitPrice:(line.unitPriceCents/100).toFixed(2)})))
const busy=ref(false);const message=ref('')
const totals=computed(()=>{try{return calculateInvoiceTotals(lines.value.map(line=>({description:line.description,quantity:line.quantity,unitPriceCents:Math.round(Number(line.unitPrice)*100)})),form.vatMode,form.vatRateBasisPoints)}catch{return null}})
function money(cents:number){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:form.currency}).format(cents/100)}
function clientName(){return invoice.clientCompanyName||[invoice.clientFirstName,invoice.clientLastName].filter(Boolean).join(' ')||'Client'}
function setVatRate(event:Event){form.vatRateBasisPoints=Math.round(Number((event.target as HTMLInputElement).value)*100)}
function payload(){return{...form,lines:lines.value.map(line=>({description:line.description,quantity:line.quantity,unitPriceCents:Math.round(Number(line.unitPrice)*100)}))}}
async function save(){busy.value=true;message.value='';try{await $fetch(`/api/admin/invoices/${id}`,{method:'PUT',body:payload()});await refresh();message.value='Draft saved.'}catch(error:unknown){message.value=apiErrorMessage(error,'Could not save invoice.')}finally{busy.value=false}}
async function finalize(){if(!confirm('Finalize this invoice? Its number, content and PDF will become immutable.'))return;busy.value=true;try{await save();await $fetch(`/api/admin/invoices/${id}/finalize`,{method:'POST'});await refresh();message.value='Invoice finalized.'}catch(error:unknown){message.value=apiErrorMessage(error,'Could not finalize invoice.')}finally{busy.value=false}}
async function voidInvoice(){if(!confirm('Void this invoice and create an editable replacement draft?'))return;busy.value=true;try{const result=await $fetch<{replacement:{id:string}|null}>(`/api/admin/invoices/${id}/void`,{method:'POST',body:{createReplacement:true}});if(result.replacement)await navigateTo(`/admin/invoices/${result.replacement.id}`);else await refresh()}catch(error:unknown){message.value=apiErrorMessage(error,'Could not void invoice.')}finally{busy.value=false}}
useSeoMeta({title:()=>`${data.value?.invoice.invoiceNumber||'Draft invoice'} — DJ NightLight`,robots:'noindex, nofollow'})
</script>
<template><div v-if="data" class="invoice"><NuxtLink :to="`/admin/gigs/${data.invoice.gigId}`" class="back">← {{data.invoice.gigTitle}}</NuxtLink><header><div><p class="eyebrow">{{data.invoice.status}}</p><h1>{{data.invoice.invoiceNumber||'Draft invoice'}}</h1><p>{{data.invoice.gigTitle}} · {{clientName()}}</p></div><div class="actions"><a v-if="data.invoice.status!=='draft'" class="secondary" :href="`/api/admin/invoices/${id}/pdf`" target="_blank">Open PDF</a><button v-if="data.invoice.status==='finalized'" class="danger" @click="voidInvoice">Void & replace</button></div></header>
<form @submit.prevent="save"><section class="card"><h2>Invoice details</h2><div class="grid"><label>Issue date<input v-model="form.issueDate" type="date" :disabled="data.invoice.status!=='draft'"></label><label>Due date<input v-model="form.dueDate" type="date" :disabled="data.invoice.status!=='draft'"></label><label>Currency<input v-model="form.currency" maxlength="3" :disabled="data.invoice.status!=='draft'"></label><label>VAT behavior<select v-model="form.vatMode" :disabled="data.invoice.status!=='draft'"><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option><option value="exempt">Exempt</option></select></label><label>VAT rate (%)<input :value="form.vatRateBasisPoints/100" type="number" min="0" max="100" step=".01" :disabled="data.invoice.status!=='draft'" @input="setVatRate"></label></div></section>
<section class="card"><div class="section-title"><h2>Line items</h2><button v-if="data.invoice.status==='draft'" type="button" class="text" @click="lines.push({description:'',quantity:'1.000',unitPrice:'0.00'})">+ Add line</button></div><div v-for="(line,index) in lines" :key="index" class="line"><input v-model="line.description" placeholder="Description" :disabled="data.invoice.status!=='draft'"><input v-model="line.quantity" inputmode="decimal" placeholder="Quantity" :disabled="data.invoice.status!=='draft'"><input v-model="line.unitPrice" inputmode="decimal" placeholder="Unit price" :disabled="data.invoice.status!=='draft'"><button v-if="data.invoice.status==='draft'&&lines.length>1" type="button" @click="lines.splice(index,1)">×</button></div><div v-if="totals" class="totals"><span>Subtotal <strong>{{money(totals.subtotalCents)}}</strong></span><span>VAT <strong>{{money(totals.vatAmountCents)}}</strong></span><span class="grand">Total <strong>{{money(totals.totalCents)}}</strong></span></div></section>
<section class="card"><h2>Terms & notes</h2><div class="grid"><label class="wide">Payment terms<textarea v-model="form.paymentTerms" rows="3" :disabled="data.invoice.status!=='draft'"/></label><label class="wide">Legal text<textarea v-model="form.legalText" rows="3" :disabled="data.invoice.status!=='draft'"/></label><label class="wide">Notes<textarea v-model="form.notes" rows="3" :disabled="data.invoice.status!=='draft'"/></label></div></section><section class="card"><h2>Payment</h2><div class="payment-state"><strong>{{data.invoice.paymentStatus}}</strong><span v-if="data.payment">Stripe: {{data.payment.status}} · {{data.payment.attemptCount}} checkout attempt(s)<template v-if="data.payment.paidAt"> · Paid {{data.payment.paidAt}}</template></span><span v-else>No Stripe checkout has been started.</span></div></section>
<div v-if="data.invoice.status==='draft'" class="save-bar"><span>{{message||'Save changes before finalizing.'}}</span><div><button class="secondary" :disabled="busy" type="submit">Save draft</button><button class="primary" :disabled="busy||!totals" type="button" @click="finalize">Finalize invoice</button></div></div><p v-else-if="message" class="message">{{message}}</p></form></div></template>
<style scoped>.payment-state{display:flex;justify-content:space-between;gap:1rem}.payment-state strong{text-transform:capitalize}.payment-state span{color:#8c8594}@media(max-width:700px){.payment-state{align-items:stretch;flex-direction:column}}</style>
<style scoped>.invoice{max-width:1000px;margin-inline:auto}.back{display:inline-block;margin-bottom:1rem;color:#8e8797;text-decoration:none}header{display:flex;align-items:end;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}h1{margin:.2rem 0;font-size:clamp(2.4rem,6vw,4.5rem);letter-spacing:-.05em}header p:last-child{color:#8d8694}.actions{display:flex;gap:.5rem}.card{margin-bottom:1rem;padding:1.2rem;border:1px solid #2b2631;border-radius:1rem;background:#100e14}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.wide{grid-column:1/-1}label{display:grid;gap:.35rem;color:#aaa4b1;font-size:.8rem}input,select,textarea{width:100%;border:1px solid #332e39;border-radius:.65rem;padding:.7rem;background:#0b0a0d;color:#f6f3fa}input:disabled,select:disabled,textarea:disabled{opacity:.72}.section-title{display:flex;justify-content:space-between}.text{border:0;background:transparent;color:#bbb4c3}.line{display:grid;grid-template-columns:1fr 8rem 10rem 2rem;gap:.5rem;margin-top:.5rem}.line button{border:0;border-radius:.5rem;background:#2a171d;color:#e7a4ad}.totals{display:grid;gap:.4rem;justify-content:end;margin-top:1rem;min-width:280px}.totals span{display:flex;justify-content:space-between;gap:2rem}.grand{padding-top:.5rem;border-top:1px solid #332e39;font-size:1.15rem}.save-bar{position:sticky;bottom:1rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem;border:1px solid #37313d;border-radius:1rem;background:rgba(20,17,25,.96)}.save-bar>div{display:flex;gap:.5rem}.primary,.secondary,.danger{display:inline-block;border:0;border-radius:.65rem;padding:.72rem .9rem;font-weight:800;text-decoration:none}.primary{background:#fff;color:#09080b}.secondary{background:#211c27;color:#eee9f2}.danger{background:#2a1519;color:#ffabb5}.message{color:#aaa4b1}@media(max-width:700px){header,.save-bar{align-items:stretch;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.line{grid-template-columns:1fr}.actions,.save-bar>div{display:grid}.totals{justify-content:stretch}}</style>
