<script setup lang="ts">
import { calculateInvoiceTotals } from '~~/shared/invoice'
import { apiErrorMessage } from '~/utils/api-error'
import { invoiceStatusLabels, labelFor, paymentStatusLabels } from '~~/shared/labels'
definePageMeta({layout:'admin'})
const route=useRoute();const id=String(route.params.id)
type Line={id:string;description:string;quantity:string;unitPriceCents:number;ordering:number}
type Invoice={id:string;invoiceNumber:string|null;status:'draft'|'finalized'|'void';paymentStatus:string;issueDate:string;dueDate:string;currency:string;vatMode:'exclusive'|'inclusive'|'exempt';vatRateBasisPoints:number;subtotalCents:number;vatAmountCents:number;totalCents:number;paymentTerms:string;legalText:string;notes:string;documentHash:string|null;gigId:string;gigTitle:string;clientFirstName:string|null;clientLastName:string|null;clientCompanyName:string|null}
type Detail={invoice:Invoice;lines:Line[];payment:{providerSessionId:string|null;providerPaymentIntentId:string|null;status:string;attemptCount:number;paidAt:string|null;failureCode:string|null}|null}
type EditableLine={description:string;quantity:string;unitPrice:string}
const {data,refresh}=await useFetch<Detail>(`/api/admin/invoices/${id}`)
if(!data.value)throw createError({statusCode:404,statusMessage:'Factuur niet gevonden'})
const invoice=data.value.invoice
const form=reactive({issueDate:invoice.issueDate,dueDate:invoice.dueDate,currency:invoice.currency,vatMode:invoice.vatMode,vatRateBasisPoints:invoice.vatRateBasisPoints,paymentTerms:invoice.paymentTerms,legalText:invoice.legalText,notes:invoice.notes})
const lines=ref<EditableLine[]>(data.value.lines.map(line=>({description:line.description,quantity:String(line.quantity),unitPrice:(line.unitPriceCents/100).toFixed(2)})))
const busy=ref(false);const message=ref('')
const totals=computed(()=>{try{return calculateInvoiceTotals(lines.value.map(line=>({description:line.description,quantity:line.quantity,unitPriceCents:Math.round(Number(line.unitPrice)*100)})),form.vatMode,form.vatRateBasisPoints)}catch{return null}})
function money(cents:number){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:form.currency}).format(cents/100)}
function clientName(){return invoice.clientCompanyName||[invoice.clientFirstName,invoice.clientLastName].filter(Boolean).join(' ')||'Klant'}
function setVatRate(event:Event){form.vatRateBasisPoints=Math.round(Number((event.target as HTMLInputElement).value)*100)}
function payload(){return{...form,lines:lines.value.map(line=>({description:line.description,quantity:line.quantity,unitPriceCents:Math.round(Number(line.unitPrice)*100)}))}}
async function save(){busy.value=true;message.value='';try{await $fetch(`/api/admin/invoices/${id}`,{method:'PUT',body:payload()});await refresh();message.value='Concept opgeslagen.'}catch(error:unknown){message.value=apiErrorMessage(error,'Factuur opslaan is niet gelukt.')}finally{busy.value=false}}
async function finalize(){if(!confirm('Deze factuur definitief maken? Het nummer, de inhoud en de PDF kunnen daarna niet meer worden gewijzigd.'))return;busy.value=true;try{await save();await $fetch(`/api/admin/invoices/${id}/finalize`,{method:'POST'});await refresh();message.value='Factuur definitief gemaakt.'}catch(error:unknown){message.value=apiErrorMessage(error,'Factuur definitief maken is niet gelukt.')}finally{busy.value=false}}
async function voidInvoice(){if(!confirm('Deze factuur laten vervallen en een bewerkbaar vervangend concept aanmaken?'))return;busy.value=true;try{const result=await $fetch<{replacement:{id:string}|null}>(`/api/admin/invoices/${id}/void`,{method:'POST',body:{createReplacement:true}});if(result.replacement)await navigateTo(`/admin/invoices/${result.replacement.id}`);else await refresh()}catch(error:unknown){message.value=apiErrorMessage(error,'Factuur laten vervallen is niet gelukt.')}finally{busy.value=false}}
useSeoMeta({title:()=>`${data.value?.invoice.invoiceNumber||'Conceptfactuur'} — DJ NightLight`,robots:'noindex, nofollow'})
</script>
<template><div v-if="data" class="invoice"><NuxtLink :to="`/admin/gigs/${data.invoice.gigId}`" class="back"><Icon name="lucide:arrow-left" aria-hidden="true" /> {{data.invoice.gigTitle}}</NuxtLink><header><div><p class="eyebrow">{{labelFor(invoiceStatusLabels,data.invoice.status)}}</p><h1>{{data.invoice.invoiceNumber||'Conceptfactuur'}}</h1><p>{{data.invoice.gigTitle}} · {{clientName()}}</p></div><div class="actions"><a v-if="data.invoice.status!=='draft'" class="secondary" :href="`/api/admin/invoices/${id}/pdf`" target="_blank">PDF openen</a><button v-if="data.invoice.status==='finalized'" class="danger" @click="voidInvoice">Laten vervallen & vervangen</button></div></header>
<form @submit.prevent="save"><section class="card"><h2>Factuurgegevens</h2><div class="grid"><label>Factuurdatum<input v-model="form.issueDate" type="date" :disabled="data.invoice.status!=='draft'"></label><label>Vervaldatum<input v-model="form.dueDate" type="date" :disabled="data.invoice.status!=='draft'"></label><label>Valuta<input v-model="form.currency" maxlength="3" :disabled="data.invoice.status!=='draft'"></label><label>Btw-berekening<select v-model="form.vatMode" :disabled="data.invoice.status!=='draft'"><option value="exclusive">Exclusief btw</option><option value="inclusive">Inclusief btw</option><option value="exempt">Vrijgesteld van btw</option></select></label><label>Btw-tarief (%)<input :value="form.vatRateBasisPoints/100" type="number" min="0" max="100" step=".01" :disabled="data.invoice.status!=='draft'" @input="setVatRate"></label></div></section>
<section class="card"><div class="section-title"><h2>Factuurregels</h2><button v-if="data.invoice.status==='draft'" type="button" class="text" @click="lines.push({description:'',quantity:'1.000',unitPrice:'0.00'})"><Icon name="lucide:plus" aria-hidden="true" /> Regel toevoegen</button></div><div v-for="(line,index) in lines" :key="index" class="line"><input v-model="line.description" placeholder="Omschrijving" :disabled="data.invoice.status!=='draft'"><input v-model="line.quantity" inputmode="decimal" placeholder="Aantal" :disabled="data.invoice.status!=='draft'"><input v-model="line.unitPrice" inputmode="decimal" placeholder="Prijs per stuk" :disabled="data.invoice.status!=='draft'"><button v-if="data.invoice.status==='draft'&&lines.length>1" type="button" aria-label="Regel verwijderen" title="Regel verwijderen" @click="lines.splice(index,1)"><Icon name="lucide:x" aria-hidden="true" /></button></div><div v-if="totals" class="totals"><span>Subtotaal <strong>{{money(totals.subtotalCents)}}</strong></span><span>Btw <strong>{{money(totals.vatAmountCents)}}</strong></span><span class="grand">Totaal <strong>{{money(totals.totalCents)}}</strong></span></div></section>
<section class="card"><h2>Voorwaarden & notities</h2><div class="grid"><label class="wide">Betalingsvoorwaarden<textarea v-model="form.paymentTerms" rows="3" :disabled="data.invoice.status!=='draft'"/></label><label class="wide">Juridische tekst<textarea v-model="form.legalText" rows="3" :disabled="data.invoice.status!=='draft'"/></label><label class="wide">Notities<textarea v-model="form.notes" rows="3" :disabled="data.invoice.status!=='draft'"/></label></div></section><section class="card"><h2>Betaling</h2><div class="payment-state"><strong>{{labelFor(paymentStatusLabels,data.invoice.paymentStatus)}}</strong><span v-if="data.payment">Stripe: {{labelFor(paymentStatusLabels,data.payment.status)}} · {{data.payment.attemptCount}} betaalpoging(en)<template v-if="data.payment.paidAt"> · Betaald {{data.payment.paidAt}}</template></span><span v-else>Er is nog geen Stripe Checkout gestart.</span></div></section>
<div v-if="data.invoice.status==='draft'" class="save-bar"><span>{{message||'Sla wijzigingen op voordat je de factuur definitief maakt.'}}</span><div><button class="secondary" :disabled="busy" type="submit">Concept opslaan</button><button class="primary" :disabled="busy||!totals" type="button" @click="finalize">Factuur definitief maken</button></div></div><p v-else-if="message" class="message">{{message}}</p></form></div></template>
<style scoped>.payment-state{display:flex;justify-content:space-between;gap:1rem}.payment-state span{color:#8c8594}@media(max-width:700px){.payment-state{align-items:stretch;flex-direction:column}}</style>
<style scoped>.invoice{max-width:1000px;margin-inline:auto}.back{display:inline-block;margin-bottom:1rem;color:#8e8797;text-decoration:none}header{display:flex;align-items:end;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}h1{margin:.2rem 0;font-size:clamp(2.4rem,6vw,4.5rem);letter-spacing:-.05em}header p:last-child{color:#8d8694}.actions{display:flex;gap:.5rem}.card{margin-bottom:1rem;padding:1.2rem;border:1px solid #2b2631;border-radius:1rem;background:#100e14}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.wide{grid-column:1/-1}label{display:grid;gap:.35rem;color:#aaa4b1;font-size:.8rem}input,select,textarea{width:100%;border:1px solid #332e39;border-radius:.65rem;padding:.7rem;background:#0b0a0d;color:#f6f3fa}input:disabled,select:disabled,textarea:disabled{opacity:.72}.section-title{display:flex;justify-content:space-between}.text{border:0;background:transparent;color:#bbb4c3}.line{display:grid;grid-template-columns:1fr 8rem 10rem 2rem;gap:.5rem;margin-top:.5rem}.line button{border:0;border-radius:.5rem;background:#2a171d;color:#e7a4ad}.totals{display:grid;gap:.4rem;justify-content:end;margin-top:1rem;min-width:280px}.totals span{display:flex;justify-content:space-between;gap:2rem}.grand{padding-top:.5rem;border-top:1px solid #332e39;font-size:1.15rem}.save-bar{position:sticky;bottom:1rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem;border:1px solid #37313d;border-radius:1rem;background:rgba(20,17,25,.96)}.save-bar>div{display:flex;gap:.5rem}.primary,.secondary,.danger{display:inline-block;border:0;border-radius:.65rem;padding:.72rem .9rem;font-weight:800;text-decoration:none}.primary{background:#fff;color:#09080b}.secondary{background:#211c27;color:#eee9f2}.danger{background:#2a1519;color:#ffabb5}.message{color:#aaa4b1}@media(max-width:700px){header,.save-bar{align-items:stretch;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.line{grid-template-columns:1fr}.actions,.save-bar>div{display:grid}.totals{justify-content:stretch}}</style>
