<script setup lang="ts">
import { calculateInvoiceTotals } from '~~/shared/invoice'
import { apiErrorMessage } from '~/utils/api-error'
import { invoiceStatusLabels, labelFor, paymentStatusLabels } from '~~/shared/labels'
import { manualPaymentMethodLabels, manualPaymentMethods } from '~~/shared/schemas/manual-payment'
definePageMeta({layout:'admin'})
const route=useRoute();const id=String(route.params.id)
type Line={id:string;description:string;quantity:string;unitPriceCents:number;ordering:number}
type Invoice={id:string;invoiceNumber:string|null;status:'draft'|'finalized'|'void';paymentStatus:string;issueDate:string;dueDate:string;currency:string;vatMode:'exclusive'|'inclusive'|'exempt';vatRateBasisPoints:number;subtotalCents:number;vatAmountCents:number;totalCents:number;paymentTerms:string;legalText:string;notes:string;documentHash:string|null;gigId:string;gigTitle:string;clientFirstName:string|null;clientLastName:string|null;clientCompanyName:string|null}
type Detail={invoice:Invoice&{clientEmail:string|null};lines:Line[];payment:{provider:string;providerSessionId:string|null;providerPaymentIntentId:string|null;status:string;attemptCount:number;paidAt:string|null;failureCode:string|null;metadata:{method?:keyof typeof manualPaymentMethodLabels;note?:string}|null}|null}
type EditableLine={description:string;quantity:string;unitPrice:string}
const {data,refresh}=await useFetch<Detail>(`/api/admin/invoices/${id}`)
if(!data.value)throw createError({statusCode:404,statusMessage:'Factuur niet gevonden'})
const invoice=data.value.invoice
const form=reactive({issueDate:invoice.issueDate,dueDate:invoice.dueDate,currency:invoice.currency,vatMode:invoice.vatMode,vatRateBasisPoints:invoice.vatRateBasisPoints,paymentTerms:invoice.paymentTerms,legalText:invoice.legalText,notes:invoice.notes})
const lines=ref<EditableLine[]>(data.value.lines.map(line=>({description:line.description,quantity:String(Number(line.quantity)),unitPrice:(line.unitPriceCents/100).toFixed(2)})))
const busy=ref(false);const message=ref('')
const totals=computed(()=>{try{return calculateInvoiceTotals(lines.value.map(line=>({description:line.description,quantity:line.quantity,unitPriceCents:Math.round(Number(line.unitPrice)*100)})),form.vatMode,form.vatRateBasisPoints)}catch{return null}})
function money(cents:number){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:form.currency}).format(cents/100)}
function clientName(){return invoice.clientCompanyName||[invoice.clientFirstName,invoice.clientLastName].filter(Boolean).join(' ')||'Klant'}
function setVatRate(event:Event){form.vatRateBasisPoints=Math.round(Number((event.target as HTMLInputElement).value)*100)}
function payload(){return{...form,lines:lines.value.map(line=>({description:line.description,quantity:line.quantity,unitPriceCents:Math.round(Number(line.unitPrice)*100)}))}}
async function save(){busy.value=true;message.value='';try{await $fetch(`/api/admin/invoices/${id}`,{method:'PUT',body:payload()});await refresh();message.value='Concept opgeslagen.'}catch(error:unknown){message.value=apiErrorMessage(error,'Factuur opslaan is niet gelukt.')}finally{busy.value=false}}
type FinalizeCheck={blockers:string[];email:{recipient:string|null;willSend:boolean;skipReason:string|null;delayMinutes:number;providerConfigured:boolean}}
const finalizeDialog=ref<HTMLDialogElement|null>(null);const check=ref<FinalizeCheck|null>(null);const checkError=ref('')
// Finalizing locks the invoice and emails it to the client, so it goes through a dialog that shows both before anything happens.
async function openFinalize(){busy.value=true;message.value='';checkError.value='';check.value=null;try{await $fetch(`/api/admin/invoices/${id}`,{method:'PUT',body:payload()});await refresh();check.value=await $fetch<FinalizeCheck>(`/api/admin/invoices/${id}/finalize-check`)}catch(error:unknown){checkError.value=apiErrorMessage(error,'De factuur kon niet worden gecontroleerd.')}finally{busy.value=false}await nextTick();finalizeDialog.value?.showModal()}
function closeFinalize(){finalizeDialog.value?.close()}
function sendMoment(minutes:number){if(minutes<=0)return'direct';if(minutes%1440===0)return`${minutes/1440} dag${minutes===1440?'':'en'} later`;if(minutes%60===0)return`${minutes/60} uur later`;return`${minutes} minuten later`}
async function finalize(){busy.value=true;try{const result=await $fetch<{invoice:{invoiceNumber:string|null};email:{recipient:string;runAt:string}|null}>(`/api/admin/invoices/${id}/finalize`,{method:'POST'});closeFinalize();await refresh();const number=result.invoice.invoiceNumber||'De factuur';message.value=result.email?(new Date(result.email.runAt).getTime()<=Date.now()+60_000?`${number} is definitief en wordt verstuurd naar ${result.email.recipient}.`:`${number} is definitief. De e-mail naar ${result.email.recipient} staat ingepland.`):`${number} is definitief gemaakt. Er is geen e-mail verstuurd.`}catch(error:unknown){checkError.value=apiErrorMessage(error,'Factuur definitief maken is niet gelukt.')}finally{busy.value=false}}
const confirmAction=useConfirm()
// Bank transfers and cash never reach Stripe, so they are recorded here; reminders stop once the invoice is paid.
const paidDialog=ref<HTMLDialogElement|null>(null)
const paidForm=reactive({paidOn:'',method:'bank_transfer' as (typeof manualPaymentMethods)[number],note:'',sendConfirmation:false})
const paidError=ref('')
function todayIso(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Amsterdam'}).format(new Date())}
function openMarkPaid(){Object.assign(paidForm,{paidOn:todayIso(),method:'bank_transfer',note:'',sendConfirmation:false});paidError.value='';paidDialog.value?.showModal()}
async function markPaid(){busy.value=true;paidError.value='';try{const result=await $fetch<{email:{recipient:string}|null}>(`/api/admin/invoices/${id}/mark-paid`,{method:'POST',body:paidForm});paidDialog.value?.close();await refresh();message.value=result.email?`Betaling geregistreerd. De bevestiging gaat naar ${result.email.recipient}.`:'Betaling geregistreerd. Betaalherinneringen worden niet meer verstuurd.'}catch(error:unknown){paidError.value=apiErrorMessage(error,'Betaling registreren is niet gelukt.')}finally{busy.value=false}}
async function markUnpaid(){if(!(await confirmAction({title:'Betaling terugdraaien?',body:'De factuur staat daarna weer op onbetaald en betaalherinneringen worden weer verstuurd.',confirmLabel:'Terugdraaien',tone:'danger'})))return;busy.value=true;try{await $fetch(`/api/admin/invoices/${id}/mark-unpaid`,{method:'POST'});await refresh();message.value='De handmatige betaling is teruggedraaid.'}catch(error:unknown){message.value=apiErrorMessage(error,'Terugdraaien is niet gelukt.')}finally{busy.value=false}}
function formatDay(value:string|null){return value?new Intl.DateTimeFormat('nl-NL',{dateStyle:'long',timeZone:'Europe/Amsterdam'}).format(new Date(value)):''}
async function voidInvoice(){if(!(await confirmAction({title:'Factuur laten vervallen?',body:'Deze factuur vervalt en je krijgt een bewerkbaar vervangend concept. Het oude nummer blijft bewaard.',confirmLabel:'Laten vervallen',tone:'danger'})))return;busy.value=true;try{const result=await $fetch<{replacement:{id:string}|null}>(`/api/admin/invoices/${id}/void`,{method:'POST',body:{createReplacement:true}});if(result.replacement)await navigateTo(`/admin/invoices/${result.replacement.id}`);else await refresh()}catch(error:unknown){message.value=apiErrorMessage(error,'Factuur laten vervallen is niet gelukt.')}finally{busy.value=false}}
useSeoMeta({title:()=>`${data.value?.invoice.invoiceNumber||'Conceptfactuur'} — DJ NightLight`,robots:'noindex, nofollow'})
</script>
<template><div v-if="data" class="invoice"><NuxtLink :to="`/admin/gigs/${data.invoice.gigId}`" class="back"><Icon name="lucide:arrow-left" aria-hidden="true" /> {{data.invoice.gigTitle}}</NuxtLink><header><div><p class="eyebrow">{{labelFor(invoiceStatusLabels,data.invoice.status)}}</p><h1>{{data.invoice.invoiceNumber||'Conceptfactuur'}}</h1><p>{{data.invoice.gigTitle}} · {{clientName()}}</p></div><div class="actions"><a v-if="data.invoice.status!=='draft'" class="secondary" :href="`/api/admin/invoices/${id}/pdf`" target="_blank">PDF openen</a><button v-if="data.invoice.status==='finalized'" class="danger" @click="voidInvoice">Laten vervallen & vervangen</button></div></header>
<form @submit.prevent="save"><section class="card"><h2>Factuurgegevens</h2><div class="grid"><label>Factuurdatum<input v-model="form.issueDate" type="date" :disabled="data.invoice.status!=='draft'"></label><label>Vervaldatum<input v-model="form.dueDate" type="date" :disabled="data.invoice.status!=='draft'"></label><label>Valuta<input v-model="form.currency" maxlength="3" :disabled="data.invoice.status!=='draft'"></label><label>Btw-berekening<select v-model="form.vatMode" :disabled="data.invoice.status!=='draft'"><option value="exclusive">Exclusief btw</option><option value="inclusive">Inclusief btw</option><option value="exempt">Vrijgesteld van btw</option></select></label><label>Btw-tarief (%)<input :value="form.vatRateBasisPoints/100" type="number" min="0" max="100" step=".01" :disabled="data.invoice.status!=='draft'" @input="setVatRate"></label></div></section>
<section class="card"><div class="section-title"><h2>Factuurregels</h2><button v-if="data.invoice.status==='draft'" type="button" class="text" @click="lines.push({description:'',quantity:'1',unitPrice:'0.00'})"><Icon name="lucide:plus" aria-hidden="true" /> Regel toevoegen</button></div><div v-for="(line,index) in lines" :key="index" class="line"><input v-model="line.description" :aria-label="`Omschrijving regel ${index+1}`" placeholder="Omschrijving" :disabled="data.invoice.status!=='draft'"><input v-model="line.quantity" :aria-label="`Aantal regel ${index+1}`" inputmode="decimal" placeholder="Aantal" :disabled="data.invoice.status!=='draft'"><input v-model="line.unitPrice" :aria-label="`Prijs per stuk regel ${index+1}`" inputmode="decimal" placeholder="Prijs per stuk" :disabled="data.invoice.status!=='draft'"><button v-if="data.invoice.status==='draft'&&lines.length>1" type="button" aria-label="Regel verwijderen" title="Regel verwijderen" @click="lines.splice(index,1)"><Icon name="lucide:x" aria-hidden="true" /></button></div><div v-if="totals" class="totals"><span>Subtotaal <strong>{{money(totals.subtotalCents)}}</strong></span><span>Btw <strong>{{money(totals.vatAmountCents)}}</strong></span><span class="grand">Totaal <strong>{{money(totals.totalCents)}}</strong></span></div></section>
<section class="card"><h2>Voorwaarden & notities</h2><div class="grid"><label class="wide">Betalingsvoorwaarden<textarea v-model="form.paymentTerms" rows="3" :disabled="data.invoice.status!=='draft'"/></label><label class="wide">Juridische tekst<textarea v-model="form.legalText" rows="3" :disabled="data.invoice.status!=='draft'"/></label><label class="wide">Notities<textarea v-model="form.notes" rows="3" :disabled="data.invoice.status!=='draft'"/></label></div></section><section class="card"><h2>Betaling</h2><div class="payment-state"><div><strong>{{labelFor(paymentStatusLabels,data.invoice.paymentStatus)}}</strong><span v-if="data.payment?.provider==='manual'">Handmatig geregistreerd: {{data.payment.metadata?.method?manualPaymentMethodLabels[data.payment.metadata.method]:'betaling'}} op {{formatDay(data.payment.paidAt)}}<template v-if="data.payment.metadata?.note"> · {{data.payment.metadata.note}}</template></span><span v-else-if="data.payment">Online (Stripe): {{labelFor(paymentStatusLabels,data.payment.status)}}<template v-if="data.payment.paidAt"> op {{formatDay(data.payment.paidAt)}}</template></span><span v-else-if="data.invoice.status==='finalized'">Nog geen betaling ontvangen. Betaalt de klant per overschrijving of contant, registreer het dan hier.</span><span v-else>Betalen kan zodra de factuur definitief is.</span></div><button v-if="data.invoice.status==='finalized'&&data.invoice.paymentStatus!=='paid'" type="button" class="primary" :disabled="busy" @click="openMarkPaid">Markeer als betaald</button><button v-else-if="data.payment?.provider==='manual'" type="button" class="secondary" :disabled="busy" @click="markUnpaid">Betaling terugdraaien</button></div></section>
<div v-if="data.invoice.status==='draft'" class="save-bar"><span>{{message||'Bij definitief maken wordt het concept eerst opgeslagen.'}}</span><div><button class="secondary" :disabled="busy" type="submit">Concept opslaan</button><button class="primary" :disabled="busy||!totals" type="button" @click="openFinalize">Definitief maken…</button></div></div><p v-else-if="message" class="message" role="status">{{message}}</p></form>
<dialog ref="finalizeDialog" class="finalize-dialog" aria-labelledby="finalize-title" @cancel="busy&&$event.preventDefault()"><h2 id="finalize-title">Factuur definitief maken</h2><p class="dialog-lead">{{clientName()}} · <strong>{{totals?money(totals.totalCents):''}}</strong></p>
<p v-if="checkError" class="dialog-error" role="alert">{{checkError}}</p>
<template v-if="check"><div v-if="check.blockers.length" class="blockers" role="alert"><strong>Dit moet eerst kloppen</strong><ul><li v-for="blocker in check.blockers" :key="blocker">{{blocker}}</li></ul><NuxtLink to="/admin/settings">Bedrijfsgegevens openen</NuxtLink></div>
<template v-else><ul class="consequences"><li><Icon name="lucide:lock" aria-hidden="true" /><span>De factuur krijgt een nummer. Inhoud en PDF zijn daarna niet meer te wijzigen; corrigeren kan alleen door te laten vervallen en te vervangen.</span></li>
<li v-if="check.email.willSend"><Icon name="lucide:send" aria-hidden="true" /><span>De factuur wordt <strong>{{sendMoment(check.email.delayMinutes)}}</strong> gemaild naar <strong>{{check.email.recipient}}</strong>.<template v-if="!check.email.providerConfigured"> Let op: er is nog geen e-mailprovider ingesteld, dus de e-mail blijft in de wachtrij staan tot dat geregeld is.</template></span></li>
<li v-else><Icon name="lucide:mail-x" aria-hidden="true" /><span>Er wordt geen e-mail verstuurd. {{check.email.skipReason}}</span></li></ul>
<a class="preview-link" :href="`/api/admin/invoices/${id}/pdf?preview=1`" target="_blank" rel="noopener">Bekijk PDF-voorbeeld <Icon name="lucide:external-link" aria-hidden="true" /></a></template></template>
<div class="dialog-actions"><button type="button" class="secondary" autofocus :disabled="busy" @click="closeFinalize">Annuleren</button><button type="button" class="primary" :disabled="busy||!check||check.blockers.length>0" @click="finalize">{{check?.email.willSend?'Definitief maken & versturen':'Definitief maken'}}</button></div></dialog>
<dialog ref="paidDialog" class="finalize-dialog" aria-labelledby="paid-title"><form @submit.prevent="markPaid"><h2 id="paid-title">Betaling registreren</h2><p class="dialog-lead">{{clientName()}} · <strong>{{money(data.invoice.totalCents)}}</strong></p>
<div class="paid-grid"><label>Betaald op<input v-model="paidForm.paidOn" type="date" required :max="todayIso()"></label><label>Hoe<select v-model="paidForm.method"><option v-for="method in manualPaymentMethods" :key="method" :value="method">{{manualPaymentMethodLabels[method]}}</option></select></label><label class="wide">Notitie <small>optioneel</small><input v-model="paidForm.note" maxlength="500" placeholder="Bijv. kenmerk van de overschrijving"></label></div>
<label v-if="data.invoice.clientEmail" class="check"><input v-model="paidForm.sendConfirmation" type="checkbox"> Stuur {{data.invoice.clientEmail}} een bevestiging van de betaling</label>
<p class="dialog-note">Geplande betaalherinneringen voor deze factuur worden niet meer verstuurd.</p>
<p v-if="paidError" class="dialog-error" role="alert">{{paidError}}</p>
<div class="dialog-actions"><button type="button" class="secondary" :disabled="busy" @click="paidDialog?.close()">Annuleren</button><button type="submit" class="primary" :disabled="busy">Betaling registreren</button></div></form></dialog></div></template>
<style scoped>.finalize-dialog{width:min(34rem,calc(100% - 2rem));padding:1.4rem;border:1px solid #37313d;border-radius:1rem;background:#141119;color:var(--text)}.finalize-dialog::backdrop{background:rgba(5,4,7,.72)}.finalize-dialog h2{margin:0 0 .35rem;font-size:1.35rem}.dialog-lead{margin:0 0 1.1rem;color:var(--text-muted)}.dialog-lead strong{color:var(--text)}.consequences{display:grid;gap:.85rem;margin:0 0 1.1rem;padding:0;list-style:none}.consequences li{display:grid;grid-template-columns:1.1rem 1fr;gap:.7rem;align-items:start;color:#cfc9d5;line-height:1.5}.consequences svg{margin-top:.2rem;color:#b48cff}.consequences strong{color:#fff}.blockers{margin-bottom:1.1rem;padding:.9rem 1rem;border:1px solid #5a2a33;border-radius:.75rem;background:#22121a;color:#ffd5db}.blockers ul{margin:.5rem 0;padding-left:1.1rem;line-height:1.5}.blockers a,.preview-link{color:#d9c6ff}.preview-link{display:inline-flex;align-items:center;gap:.35rem}.dialog-error{color:#ffabb5}.dialog-actions{display:flex;justify-content:flex-end;gap:.5rem;margin-top:1.25rem}@media(max-width:700px){.dialog-actions{flex-direction:column-reverse}}.payment-state{display:flex;align-items:center;justify-content:space-between;gap:1rem}.payment-state>div{display:grid;gap:.3rem}.payment-state span{color:var(--text-muted)}.paid-grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem;margin-bottom:1rem}.paid-grid .wide{grid-column:1/-1}.paid-grid small{color:var(--text-subtle)}.check{display:flex;align-items:center;gap:.6rem;margin-bottom:.6rem;color:var(--text-muted);font-size:.86rem}.check input{width:auto}.dialog-note{margin:.4rem 0 0;color:var(--text-subtle);font-size:.82rem}@media(max-width:520px){.paid-grid{grid-template-columns:1fr}}@media(max-width:700px){.payment-state{align-items:stretch;flex-direction:column}}</style>
<style scoped>.invoice{max-width:1000px;margin-inline:auto}.back{display:inline-block;margin-bottom:1rem;color:#8e8797;text-decoration:none}header{display:flex;align-items:end;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}h1{margin:.2rem 0;font-size:clamp(2.4rem,6vw,4.5rem);letter-spacing:-.04em}header p:last-child{color:#8d8694}.actions{display:flex;gap:.5rem}.card{margin-bottom:1rem;padding:1.2rem;border:1px solid var(--border);border-radius:1rem;background:var(--surface-card)}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.wide{grid-column:1/-1}label{display:grid;gap:.35rem;color:var(--text-muted);font-size:.8rem}input,select,textarea{width:100%;border:1px solid var(--border-strong);border-radius:.65rem;padding:.7rem;background:var(--surface-input);color:var(--text)}input:disabled,select:disabled,textarea:disabled{opacity:.72}.section-title{display:flex;justify-content:space-between}.text{border:0;background:transparent;color:#bbb4c3}.line{display:grid;grid-template-columns:1fr 8rem 10rem 2rem;gap:.5rem;margin-top:.5rem}.line button{border:0;border-radius:.5rem;background:#2a171d;color:#e7a4ad}.totals{display:grid;gap:.4rem;justify-content:end;margin-top:1rem;min-width:280px}.totals span{display:flex;justify-content:space-between;gap:2rem}.grand{padding-top:.5rem;border-top:1px solid var(--border-strong);font-size:1.15rem}.save-bar{position:sticky;bottom:1rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem;border:1px solid #37313d;border-radius:1rem;background:rgba(20,17,25,.96)}.save-bar>div{display:flex;gap:.5rem}.primary,.secondary,.danger{display:inline-block;border:0;border-radius:.65rem;padding:.72rem .9rem;font-weight:800;text-decoration:none}.primary{background:var(--button-primary-bg);color:var(--button-primary-fg)}.primary:disabled,.secondary:disabled,.danger:disabled{opacity:.45;cursor:not-allowed}.secondary{background:var(--button-secondary-bg);color:var(--button-secondary-fg)}.danger{background:var(--button-danger-bg);color:var(--button-danger-fg)}.message{color:var(--text-muted)}@media(max-width:700px){header,.save-bar{align-items:stretch;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.line{grid-template-columns:1fr}.actions,.save-bar>div{display:grid}.totals{justify-content:stretch}}</style>
