<script setup lang="ts">
import { invoiceStatusLabels, labelFor, paymentStatusLabels } from '~~/shared/labels'

definePageMeta({layout:'admin'})
type Invoice={id:string;invoiceNumber:string|null;status:string;paymentStatus:string;issueDate:string;dueDate:string;totalCents:number;currency:string;gigId:string;gigTitle:string;clientFirstName:string|null;clientLastName:string|null;clientCompanyName:string|null}
const {data}=await useFetch<{invoices:Invoice[]}>('/api/admin/invoices')
function clientName(item:Invoice){return item.clientCompanyName||[item.clientFirstName,item.clientLastName].filter(Boolean).join(' ')||'Klant'}
function money(cents:number,currency:string){return new Intl.NumberFormat('nl-NL',{style:'currency',currency}).format(cents/100)}
useSeoMeta({title:'Facturen — DJ NightLight',robots:'noindex, nofollow'})
</script>
<template><div class="invoices"><header><p class="eyebrow">Financiën</p><h1>Facturen</h1><p>Maak facturen aan vanuit een gig en maak ze hier definitief.</p></header><div v-if="!data?.invoices.length" class="empty">Nog geen facturen. Open een gig om er een aan te maken.</div><NuxtLink v-for="invoice in data?.invoices||[]" :key="invoice.id" :to="`/admin/invoices/${invoice.id}`" class="row"><div><strong>{{invoice.invoiceNumber||'Conceptfactuur'}}</strong><span>{{invoice.gigTitle}} · {{clientName(invoice)}}</span></div><div class="states"><span>{{labelFor(invoiceStatusLabels,invoice.status)}}</span><span>{{labelFor(paymentStatusLabels,invoice.paymentStatus)}}</span></div><strong>{{money(invoice.totalCents,invoice.currency)}}</strong></NuxtLink></div></template>
<style scoped>.invoices{max-width:1000px;margin-inline:auto}header{margin-bottom:1.5rem}h1{margin:.2rem 0;font-size:clamp(2.5rem,6vw,4.5rem);letter-spacing:-.05em}header>p:last-child{color:#8c8594}.row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:1rem;align-items:center;padding:1rem;border:1px solid #2b2631;border-radius:.85rem;margin-bottom:.6rem;background:#100e14;text-decoration:none}.row div:first-child strong,.row div:first-child span{display:block}.row div:first-child span{color:#837c8b;font-size:.78rem}.states{display:flex;gap:.35rem}.states span{padding:.25rem .45rem;border-radius:999px;background:#211b28;color:#aaa2b2;font-size:.68rem}.empty{padding:2rem;border:1px dashed #302a36;border-radius:1rem;color:#8a8391}@media(max-width:650px){.row{grid-template-columns:1fr}.states{order:3}}</style>
