import { sitePublicCopySchema, type SiteContentInput, type SitePublicCopy } from '../../shared/schemas/site-content'

export const defaultPublicCopy: SitePublicCopy = {
  navigation: {
    home: 'Home',
    about: 'Over',
    media: 'Media',
    agenda: 'Agenda',
    booking: 'Boeken',
    menu: 'Menu',
    close: 'Sluit',
    mobileEyebrow: 'Een avond plannen?',
    mobileBooking: 'Boek NightLight →',
  },
  footer: {
    eyebrow: 'DJ NightLight · Groningen',
    title: 'Van eerste plaat\ntot laatste dans.',
    cta: 'Vertel over je feest',
    location: 'Groningen · Nederland',
    instagram: 'Instagram ↗',
    spotify: 'Spotify ↗',
    email: 'E-mail',
  },
  home: {
    secondaryCta: 'Bekijk media',
    heroCaption: 'NightLight · van achtergrond naar dansvloer',
    scrollLabel: 'Scroll ↓',
    visualEyebrow: 'NightLight in de zaal',
    visualBody: 'Een paar momenten van echte avonden met NightLight achter de booth.',
    visualCaption: 'Tijdens het draaien kijk ik vooral naar wat er op de vloer gebeurt.',
    aboutCta: 'Meer over NightLight →',
    aboutImageCaption: 'Ik bereid de avond voor, maar laat de volgorde afhangen van wat er in de zaal gebeurt.',
    servicesEyebrow: 'Waar ik draai',
    servicesBody: 'Bruiloft, studentennacht of bedrijfsfeest: de muziek en opbouw verschillen per publiek en moment.',
    proofEyebrow: 'Zo draai ik',
    proofQuote: 'Ik werk niet met één vaste setlist. Ik bereid de avond voor, maar beslis in de zaal welke richting werkt.',
    proofTags: ['Bruiloften', 'Clubs', 'Studentenfeesten', 'Bedrijfsfeesten', 'Privé-events'],
    bookingCta: 'Vertel over je feest',
  },
  about: {
    imageEyebrow: 'NightLight',
    imageCaption: 'Allround, maar nooit willekeurig.',
    storyTitle: 'De muziek volgt niet de playlist.\nDe muziek volgt de avond.',
    storyBody1: 'De set volgt de avond: achtergrond waar het moet, herkenning wanneer de groep samenkomt en energie zodra de dansvloer er klaar voor is.',
    storyBody2: 'Dat betekent soms langer wachten met die ene grote plaat. Soms juist eerder schakelen dan gepland. De zaal geeft het tempo aan.',
    momentEyebrow: 'Het moment',
    momentQuote: 'Een goede overgang hoor je. Een goede avond voel je.',
    momentBody: 'Van achtergrondmuziek naar een volle vloer — zonder dat de avond geforceerd voelt.',
    principlesEyebrow: 'Hoe NightLight draait',
    principlesTitle: 'Lezen. Opbouwen. Schakelen.',
    principles: [
      { title: 'Lezen', body: 'Geen vooraf dichtgetimmerde playlist. Eerst kijken wat de zaal nodig heeft.' },
      { title: 'Opbouwen', body: 'Een feest hoeft niet om 20:00 al op 100%. De energie mag groeien.' },
      { title: 'Schakelen', body: 'Van klassieker naar house, van pop naar guilty pleasure — zolang de overgang klopt.' },
    ],
    ctaEyebrow: 'Jouw avond',
    ctaTitle: 'Genoeg over de DJ.\nWat ga jij vieren?',
    ctaLabel: 'Vertel over je feest',
  },
  media: {
    typeLabels: ['Foto', 'Video', 'Showreel'],
    showreelEyebrow: 'Featured · Showreel',
    showreelExternalLabel: 'Bekijk extern ↗',
    showreelTitle: 'NightLight in beweging.',
    showreelBody: 'Van eerste binnenkomst tot volle dansvloer.',
    galleryEyebrow: 'Selectie',
    imageSingular: 'beeld',
    imagePlural: 'beelden',
    emptyEyebrow: 'Media library',
    emptyTitle: 'De beelden\nkomen eraan.',
    emptyBody: "Foto's, clips en showreels verschijnen hier zodra de eerste NightLight-selectie vanuit het beheer is gepubliceerd.",
    emptyMeta: ['01 · Foto', '02 · Video', '03 · Showreel'],
    closeLabel: 'Sluit',
  },
  agenda: {
    statusEyebrow: 'Openbare agenda',
    loadingLabel: 'Laden…',
    dateSingular: 'datum',
    datePlural: 'data',
    statusBody: 'Besloten boekingen blijven privé en verschijnen hier nooit.',
    emptyMarkerLabel: 'OPENBAAR',
    emptyEyebrow: 'Tussen twee avonden in',
    emptyTitle: 'Even geen openbare data.',
    emptyBody: 'Dat betekent niet dat NightLight stil staat. Besloten bruiloften, bedrijfsfeesten en privé-events worden bewust niet in deze agenda getoond.',
    emptyCta: 'Plan je eigen avond',
    listEyebrow: 'Aankomende openbare shows',
    momentSingular: 'moment',
    momentPlural: 'momenten',
    footerEyebrow: 'Niet openbaar ≠ niet beschikbaar',
    footerTitle: 'Zelf iets\nte vieren?',
    footerBody: 'Stuur de datum en locatie. Dan kijken we of NightLight nog vrij is.',
    footerCta: 'Check je datum',
  },
  landing: {
    asideEyebrow: 'DJ NightLight',
    asideTitle: 'Een set die zich aanpast aan het moment.',
    asideBody: 'De concrete muziek, planning en wensen worden afgestemd op de boeking — niet op een vaste standaardset.',
    asideCta: 'Beschikbaarheid bespreken →',
  },
  booking: {
    successEyebrow: 'Ontvangen',
    successTitle: 'Je aanvraag staat in het NightLight-systeem.',
    successBody: 'Bedankt. Je gegevens zijn als nieuwe lead opgeslagen.',
    nameLabel: 'Naam',
    companyLabel: 'Bedrijf',
    emailLabel: 'E-mail',
    phoneLabel: 'Telefoon',
    eventTypeLabel: 'Soort feest',
    dateLabel: 'Datum',
    locationLabel: 'Locatie',
    messageLabel: 'Vertel iets over het feest',
    optionalLabel: 'optioneel',
    eventTypePlaceholder: 'Bruiloft, club, verjaardag…',
    locationPlaceholder: 'Plaats of locatie',
    messagePlaceholder: 'Tijden, aantal gasten, sfeer, wensen…',
    submitLabel: 'Verstuur aanvraag',
    sendingLabel: 'Versturen…',
    errorFallback: 'Je aanvraag kon niet worden verstuurd. Probeer het later opnieuw.',
  },
  visuals: {
    homeFeatureImageUrl: null,
    homeFeatureAlt: 'NightLight in de zaal',
    homeAboutImageUrl: null,
    homeAboutAlt: 'DJ NightLight tijdens een optreden',
    aboutLeadImageUrl: null,
    aboutLeadAlt: 'NightLight tijdens een avond achter de booth',
    aboutRoomImageUrl: null,
    aboutRoomAlt: 'Publiek tijdens een NightLight-avond',
    mediaShowreelImageUrl: null,
    mediaShowreelAlt: 'NightLight showreel',
  },
}

export function resolvePublicCopy(value: unknown): SitePublicCopy {
  const parsed = sitePublicCopySchema.safeParse(value)
  return parsed.success ? parsed.data : defaultPublicCopy
}

export const defaultSiteContent: SiteContentInput = {
  brandName: 'DJ NightLight',
  heroEyebrow: 'Allround DJ · Groningen',
  heroTitle: 'Van eerste plaat tot laatste dans.',
  heroBody: 'Ik draai op bruiloften, studentenfeesten, clubs en privé-events. Van achtergrondmuziek tijdens de eerste borrel tot een volle dansvloer later op de avond.',
  heroImageUrl: null,
  heroCtaLabel: 'Boek NightLight',
  aboutEyebrow: 'Over NightLight',
  aboutTitle: 'Ik ben Remco, de DJ achter NightLight.',
  aboutBody: 'Mijn set ligt niet vooraf van begin tot eind vast. Ik kijk naar wat er in de zaal gebeurt, probeer dingen uit en bouw vanuit daar verder. Soms betekent dat disco en guilty pleasures, soms house of stevige dance, en soms precies die onverwachte klassieker op het goede moment.',
  mediaEyebrow: 'Media',
  mediaTitle: 'Zie en hoor de sfeer.',
  mediaBody: "Foto's, sets en showreels komen hier samen. Nieuwe media kun je vanuit het NightLight-beheer publiceren zonder de websitecode aan te passen.",
  showreelUrl: null,
  agendaEyebrow: 'Agenda',
  agendaTitle: 'Waar draait NightLight?',
  agendaBody: 'Openbare shows verschijnen hier. Besloten boekingen blijven vanzelfsprekend privé.',
  bookingEyebrow: 'Boeken',
  bookingTitle: 'Vertel wat je aan het plannen bent.',
  bookingBody: 'Stuur de datum, locatie en het soort feest. Je aanvraag komt direct als lead in het NightLight-systeem terecht.',
  contactEmail: null,
  contactPhone: null,
  instagramUrl: null,
  spotifyUrl: null,
  seoTitle: 'DJ NightLight · DJ voor feesten, clubs en bruiloften',
  seoDescription: 'DJ NightLight uit Groningen voor bruiloften, clubs, studentenfeesten, bedrijfsfeesten en privé-events.',
  seoImageUrl: null,
  services: [
    { title: 'Bruiloften', body: 'Van ontvangst en diner tot de eerste dans en een volle vloer. Vooraf spreken we de belangrijke momenten en muziek af; de rest ontstaat op de avond zelf.', imageUrl: null, imageAlt: '' },
    { title: 'Clubs & studentenfeesten', body: 'Hier kan ik sneller schakelen: van house en pop naar guilty pleasures of stevige dance, afhankelijk van wat er op dat moment werkt.', imageUrl: null, imageAlt: '' },
    { title: 'Bedrijfs- & privéfeesten', body: 'Rustig beginnen tijdens ontvangst of borrel en daarna opschalen zodra de groep daar klaar voor is.', imageUrl: null, imageAlt: '' },
  ],
  gallery: [],
  publicCopy: defaultPublicCopy,
}
