import type { SiteContentInput } from '../../shared/schemas/site-content'

export const defaultSiteContent: SiteContentInput = {
  brandName: 'DJ NightLight',
  heroEyebrow: 'Allround DJ · Groningen',
  heroTitle: 'Van eerste plaat tot laatste dans.',
  heroBody: 'Een avond die rustig kan beginnen en precies op het juiste moment losgaat. DJ NightLight draait breed, leest de zaal en bouwt de energie op rond jouw publiek.',
  heroImageUrl: null,
  heroCtaLabel: 'Boek NightLight',
  aboutEyebrow: 'Over NightLight',
  aboutTitle: 'Niet één vaste set. Wel de juiste muziek voor de zaal.',
  aboutBody: 'DJ NightLight draait op bruiloften, clubavonden, studentenfeesten, bedrijfsfeesten en privé-events. De muziek beweegt mee met het publiek: herkenbaar waar het moet, verrassend waar het kan.',
  mediaEyebrow: 'Media',
  mediaTitle: 'Zie en hoor de sfeer.',
  mediaBody: 'Foto\'s, sets en showreels komen hier samen. Nieuwe media kun je vanuit het NightLight-beheer publiceren zonder de websitecode aan te passen.',
  showreelUrl: null,
  agendaEyebrow: 'Agenda',
  agendaTitle: 'Waar draait NightLight?',
  agendaBody: 'Openbare shows verschijnen hier. Besloten boekingen blijven vanzelfsprekend privé.',
  bookingEyebrow: 'Boeken',
  bookingTitle: 'Vertel wat je aan het plannen bent.',
  bookingBody: 'Stuur de datum, locatie en het soort feest. Je aanvraag komt direct als lead in het NightLight-systeem terecht.',
  contactEmail: null,
  contactPhone: null,
  instagramUrl: null,
  spotifyUrl: null,
  seoTitle: 'DJ NightLight · DJ voor feesten, clubs en bruiloften',
  seoDescription: 'DJ NightLight uit Groningen voor bruiloften, clubs, studentenfeesten, bedrijfsfeesten en privé-events.',
  seoImageUrl: null,
  services: [
    { title: 'Bruiloften', body: 'Van ontvangst en diner tot openingsdans en volle dansvloer, met ruimte voor jullie eigen muziek.' },
    { title: 'Clubs & studentenfeesten', body: 'Tempo, herkenning en energie. Flexibel tussen house, pop, guilty pleasures en alles wat de zaal nodig heeft.' },
    { title: 'Bedrijfs- & privéfeesten', body: 'Een muzikale opbouw die past bij de groep, de locatie en het moment.' },
  ],
  gallery: [],
}
