<script setup lang="ts">
import { apiErrorMessage } from '~/utils/api-error'

definePageMeta({layout:'admin'});const route=useRoute();const id=String(route.params.id)
type Venue={id:string;name:string;address:string|null;city:string|null;contactName:string|null;contactEmail:string|null;contactPhone:string|null;website:string|null;parkingNotes:string|null;technicalNotes:string|null;notes:string|null}
type History={id:string;title:string;status:string;startsAt:string|Date|null;clientFirstName:string|null;clientLastName:string|null;clientCompanyName:string|null}
const {data,refresh}=await useFetch<{venue:Venue,history:History[]}>(`/api/admin/venues/${id}`);if(!data.value)throw createError({statusCode:404,statusMessage:'Venue not found'})
const v=data.value.venue;const form=reactive({name:v.name,address:v.address||'',city:v.city||'',contactName:v.contactName||'',contactEmail:v.contactEmail||'',contactPhone:v.contactPhone||'',website:v.website||'',parkingNotes:v.parkingNotes||'',technicalNotes:v.technicalNotes||'',notes:v.notes||''})
const saving=ref(false);const message=ref('')
async function save(){saving.value=true;message.value='';try{await $fetch(`/api/admin/venues/${id}`,{method:'PUT',body:form});await refresh();message.value='Saved.'}catch(error:unknown){message.value=apiErrorMessage(error,'Could not save.')}finally{saving.value=false}}
async function remove(){if(!confirm('Delete this venue permanently?'))return;try{await $fetch(`/api/admin/venues/${id}`,{method:'DELETE'});await navigateTo('/admin/venues')}catch(error:unknown){message.value=apiErrorMessage(error,'Could not delete venue.')}}
function clientName(g:History){return g.clientCompanyName||[g.clientFirstName,g.clientLastName].filter(Boolean).join(' ')||'No client'}
function dateLabel(x:string|Date|null){return x?new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium'}).format(new Date(x)):'No date'}
useSeoMeta({title:'Venue — DJ NightLight',robots:'noindex, nofollow'})
</script>
<template><div v-if="data" class="detail-page"><NuxtLink to="/admin/venues" class="back">← Venues</NuxtLink><header><div><p class="eyebrow">Venue</p><h1>{{data.venue.name}}</h1></div><button class="danger" @click="remove">Delete</button></header>
<form class="editor" @submit.prevent="save"><div class="grid"><label>Name<input v-model="form.name" required></label><label>City<input v-model="form.city"></label><label class="wide">Address<input v-model="form.address"></label><label>Contact name<input v-model="form.contactName"></label><label>Contact email<input v-model="form.contactEmail" type="email"></label><label>Contact phone<input v-model="form.contactPhone"></label><label>Website<input v-model="form.website" type="url"></label><label class="wide">Parking / load-in<textarea v-model="form.parkingNotes" rows="2"/></label><label class="wide">Technical notes<textarea v-model="form.technicalNotes" rows="3"/></label><label class="wide">General notes<textarea v-model="form.notes" rows="3"/></label></div><div class="form-actions"><button class="primary" type="submit" :disabled="saving">{{saving?'Saving…':'Save changes'}}</button><span>{{message}}</span></div></form>
<section class="history"><p class="eyebrow">History</p><h2>Gigs at this venue</h2><p v-if="!data.history.length" class="empty">No gigs connected to this venue yet.</p><NuxtLink v-for="g in data.history" :key="g.id" :to="`/admin/gigs/${g.id}`" class="gig"><div><strong>{{g.title}}</strong><span>{{clientName(g)}}</span></div><div class="meta"><span>{{dateLabel(g.startsAt)}}</span><span>{{g.status}}</span></div></NuxtLink></section></div></template>
<style scoped>
.detail-page{max-width:900px;margin-inline:auto}.back{display:inline-block;margin-bottom:1.2rem;color:#8e8797;text-decoration:none}header{display:flex;justify-content:space-between;align-items:end;gap:1rem;margin-bottom:1.5rem}h1{margin:.2rem 0;font-size:clamp(2.2rem,6vw,4rem);letter-spacing:-.05em}.editor,.history{padding:1.3rem;border:1px solid #2b2631;border-radius:1rem;background:#100e14}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.9rem}label{display:grid;gap:.4rem;color:#aaa4b1;font-size:.82rem}input,textarea{width:100%;border:1px solid #332e39;border-radius:.65rem;padding:.75rem;background:#0b0a0d;color:#f6f3fa}.wide{grid-column:1/-1}.form-actions{display:flex;align-items:center;gap:1rem;margin-top:1rem;color:#8e8797}.primary,.danger{border:0;border-radius:.65rem;padding:.72rem .9rem;font-weight:800;cursor:pointer}.primary{background:#fff;color:#09080b}.danger{background:#2a1519;color:#ffabb5}.history{margin-top:1rem}.history h2{margin:.2rem 0 1rem}.gig{display:flex;justify-content:space-between;gap:1rem;padding:.9rem 0;border-top:1px solid #26212c;text-decoration:none}.gig strong,.gig span{display:block}.gig span{color:#7f7888;font-size:.8rem}.meta{text-align:right}.empty{color:#817a8b}@media(max-width:650px){header{align-items:start;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.gig{align-items:start;flex-direction:column}.meta{text-align:left}.danger{width:100%}}
</style>
